# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Check Dockerfile
        run: |
           echo "Current directory:"
           pwd

           echo "Files in current directory:"
           ls -la

           echo "Searching for Dockerfile:"
           find . -type f -name "Dockerfile" -print  
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v7
        with:
          image: shyamalgajjar2015/mywebapp1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
